apiVersion: apps/v1
kind: Deployment
metadata:
  name: appyaml
  labels:
    app: star
spec:
  replicas: 3
  selector:
    matchLabels:
      app: star
  template:
    metadata:
      labels:
        app: star
    spec:
      containers:
      - name: appyaml
        image: dhirajsingh6/dhisin:latest
        ports:
        - containerPort: 8000
