apiVersion: v1
kind: Service
metadata:
  name: webapp-service  # Updated to a more descriptive name
spec:
  type: LoadBalancer
  selector:
    app: webApp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
